name: Linter Run

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
      fail-fast: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:latest
        env:
          VALIDATE_MD: true
          VALIDATE_BASH: true

